import type { ExpressionSpecification, StyleSpecification } from "maplibre-gl";

/**
 * Night-blue base map on OpenFreeMap's free OpenStreetMap vector tiles (OpenMapTiles schema).
 * Quiet on purpose: roads and towns for orientation, so the route is the brightest thing on it.
 */
const c = {
  background: "#1d2740",
  water: "#141c30",
  waterway: "#223255",
  wood: "#1f2b43",
  urban: "#222d48",
  boundary: "#4a5a7c",
  road: "#34436a",
  roadMajor: "#44557f",
  motorway: "#5a6c98",
  rail: "#2c3a5c",
  label: "#b3bfd6",
  labelMinor: "#8391ad",
  halo: "#1d2740",
};

const roadWidth = (base: number): ExpressionSpecification => [
  "interpolate",
  ["exponential", 1.5],
  ["zoom"],
  6,
  base * 0.3,
  10,
  base,
  16,
  base * 6,
];

const font = (weight: "Regular" | "Bold") => [`Noto Sans ${weight}`];

export const darkMapStyle: StyleSpecification = {
  version: 8,
  glyphs: "https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf",
  sources: {
    openmaptiles: { type: "vector", url: "https://tiles.openfreemap.org/planet" },
  },
  layers: [
    { id: "background", type: "background", paint: { "background-color": c.background } },
    {
      id: "landuse-urban",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landuse",
      filter: ["in", ["get", "class"], ["literal", ["residential", "suburb", "neighbourhood", "commercial", "industrial"]]],
      paint: { "fill-color": c.urban },
    },
    {
      id: "landcover-wood",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landcover",
      filter: ["==", ["get", "class"], "wood"],
      paint: { "fill-color": c.wood },
    },
    {
      id: "park",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "park",
      paint: { "fill-color": c.wood, "fill-opacity": 0.7 },
    },
    {
      id: "water",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "water",
      paint: { "fill-color": c.water },
    },
    {
      id: "waterway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "waterway",
      paint: { "line-color": c.waterway, "line-width": ["interpolate", ["linear"], ["zoom"], 8, 0.5, 14, 2] },
    },
    {
      id: "boundary",
      type: "line",
      source: "openmaptiles",
      "source-layer": "boundary",
      filter: ["all", ["<=", ["get", "admin_level"], 6], ["!=", ["get", "maritime"], 1]],
      paint: { "line-color": c.boundary, "line-width": 1, "line-dasharray": [3, 2] },
    },
    {
      id: "road-minor",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 11,
      filter: ["in", ["get", "class"], ["literal", ["minor", "service", "track"]]],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: { "line-color": c.road, "line-width": roadWidth(0.5) },
    },
    {
      id: "rail",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: ["==", ["get", "class"], "rail"],
      paint: { "line-color": c.rail, "line-width": 1 },
    },
    {
      id: "road-secondary",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 8,
      filter: ["in", ["get", "class"], ["literal", ["secondary", "tertiary"]]],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: { "line-color": c.road, "line-width": roadWidth(0.8) },
    },
    {
      id: "road-primary",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: ["in", ["get", "class"], ["literal", ["primary", "trunk"]]],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: { "line-color": c.roadMajor, "line-width": roadWidth(1) },
    },
    {
      id: "road-motorway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: ["==", ["get", "class"], "motorway"],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: { "line-color": c.motorway, "line-width": roadWidth(1.2) },
    },
    {
      id: "road-ref",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "transportation_name",
      minzoom: 8,
      filter: ["all", ["has", "ref"], ["in", ["get", "class"], ["literal", ["motorway", "trunk", "primary"]]]],
      layout: {
        "symbol-placement": "line",
        "symbol-spacing": 400,
        "text-field": ["get", "ref"],
        "text-font": font("Regular"),
        "text-size": 10,
        "text-rotation-alignment": "viewport",
      },
      paint: { "text-color": c.labelMinor, "text-halo-color": c.halo, "text-halo-width": 1.5 },
    },
    {
      id: "place-village",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      minzoom: 10,
      filter: ["in", ["get", "class"], ["literal", ["village", "suburb", "hamlet"]]],
      layout: { "text-field": ["get", "name"], "text-font": font("Regular"), "text-size": 11 },
      paint: { "text-color": c.labelMinor, "text-halo-color": c.halo, "text-halo-width": 1.5 },
    },
    {
      id: "place-town",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      minzoom: 7,
      filter: ["==", ["get", "class"], "town"],
      layout: { "text-field": ["get", "name"], "text-font": font("Regular"), "text-size": ["interpolate", ["linear"], ["zoom"], 8, 11, 13, 14] },
      paint: { "text-color": c.label, "text-halo-color": c.halo, "text-halo-width": 1.5 },
    },
    {
      id: "place-city",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      filter: ["==", ["get", "class"], "city"],
      layout: { "text-field": ["get", "name"], "text-font": font("Bold"), "text-size": ["interpolate", ["linear"], ["zoom"], 6, 12, 12, 18] },
      paint: { "text-color": c.label, "text-halo-color": c.halo, "text-halo-width": 2 },
    },
  ],
};
